Script started on Sat Mar 11 09:53:56 2017
[?1034h]0;as1041388@tingande-Air: ~[01;32m[as1041388@09:53][01;33m:[01;31m~[00m$ whoami pwd
usage: whoami
]0;as1041388@tingande-Air: ~[01;32m[as1041388@09:54][01;33m:[01;31m~[00m$ git coini[Cfi[Cg -l
core.excludesfile=~/.gitignore
core.legacyheaders=false
core.quotepath=false
core.pager=less
mergetool.keepbackup=true
push.default=simple
color.ui=auto
color.interactive=auto
repack.usedeltabaseoffset=true
alias.s=status
alias.a=!git add . && git status
alias.au=!git add -u . && git status
alias.aa=!git add . && git add -u . && git status
alias.c=commit
alias.cm=commit -m
alias.ca=commit --amend
alias.ac=!git add . && git commit
alias.acm=!git add . && git commit -m
alias.l=log --graph --all --pretty=format:'%C(yellow)%h%C(cyan)%d%Creset %s %C(white)- %an, %ar%Creset'
alias.ll=log --stat --abbrev-commit
alias.lg=log --color --graph --pretty=format:'%C(bold white)%h%Creset -%C(bold green)%d%Creset %s %C(bold green)(%cr)%Creset %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative
alias.llg=log --color --graph --pretty=format:'%C(bold white)%H %d%Creset%n%s%n%+b%C(bold blue)%an <%ae>%Creset %C(bold green)%cr (%ci)' --abbrev-commit
alias.d=diff
alias.master=checkout master
alias.spull=svn rebase
alias.spush=svn dcommit
alias.alias=!git config --list | grep 'alias\.' | sed 's/alias\.\([^=]*\)=\(.*\)/\1\	 => \2/' | sort
include.path=~/.gitcinclude
include.path=.githubconfig
include.path=.gitcredential
diff.exif.textconv=exif
credential.helper=osxkeychain
]0;as1041388@tingande-Air: ~[01;32m[as1041388@09:54][01;33m:[01;31m~[00m$ git clone htpps;[K://github.com/tingan0123/lab1.git
fatal: destination path 'lab1' already exists and is not an empty directory.
]0;as1041388@tingande-Air: ~[01;32m[as1041388@09:55][01;33m:[01;31m~[00m$ exit

Script done on Sat Mar 11 09:56:02 2017
